### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by instalator** [nodeadmin/nodeadmin#37]
```
3207 verbose stack Error: node-mysql-admin@0.1.5 postinstall: `npm install --prefix ./middleware/public/`
3207 verbose stack Exit status 4294963238
3207 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
3207 verbose stack     at emitTwo (events.js:126:13)
3207 verbose stack     at EventEmitter.emit (events.js:214:7)
3207 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3207 verbose stack     at emitTwo (events.js:126:13)
3207 verbose stack     at ChildProcess.emit (events.js:214:7)
3207 verbose stack     at maybeClose (internal/child_process.js:915:16)
3207 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
3208 verbose pkgid node-mysql-admin@0.1.5
3209 verbose cwd D:\ioBroker\node_modules\ioBroker.mysql-admin
3210 verbose Windows_NT 6.1.7601
3211 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3212 verbose node v8.15.0
3213 verbose npm  v6.4.1
3214 error code ELIFECYCLE
3215 error errno 4294963238
3216 error node-mysql-admin@0.1.5 postinstall: `npm install --prefix ./middleware/public/`
3216 error Exit status 4294963238
3217 error Failed at the node-mysql-admin@0.1.5 postinstall script.
3217 error This is probably not a problem with npm. There is likely additional logging output above.
3218 verbose exit [ 4294963238, true ]
```

**Comment by caoyd** [comment]
Same problem for me
